export const ADD_VEHICLE = 'ADD_VEHICLE';
export const GET_VEHICLE = 'GET_VEHICLE';
export const GET_FAV_VEHICLE = 'GET_FAV_VEHICLE';
export const REMOVE_VEHICLE_FROM_FAV = 'REMOVE_VEHICLE_FROM_FAV';
export const ADD_VEHICLE_TO_FAV = 'ADD_VEHICLE_TO_FAV';
